---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by macarthur.
--- DateTime: 8/18/20 1:11 PM
---
function PointToTile(x, y, tileSize, left, top, mapWidth, mapHeight)
	-- Tiles are rendered from the center so we adjust for this.
	x = x + tileSize / 2
	y = y - tileSize / 2
	-- Clamp the point to the bounds of the map
	x = math.max(left, x)
	y = math.min(top, y)
	x = math.min(left + (mapWidth * tileSize) - 1, x)
	y = math.max(top - (mapHeight * tileSize) + 1, y)
	-- Map from the bounded point to a tile
	local tileX = math.floor((x - left) / tileSize)
	local tileY = math.floor((top - y) / tileSize)
	return tileX, tileY
end