---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by macarthur.
--- DateTime: 8/22/20 12:08 PM
---
World = Class{}
function World:init()

	self.map = sti("map.lua", { "bump" })
	world = bump.newWorld(16)

	-- Prepare collision objects
	self.map:bump_init(world)

	self.map:addCustomLayer("Sprite Layer", 3)
	local objX, objY = 0,0
	-- Add data to Custom Layer
	local spriteLayer = self.map.layers["Sprite Layer"]
	for _, object in pairs(self.map.objects) do
		if object.type == "spawn" then
			objX = object.x
			objY = object.y
		end
	end
	gPlayer = {
		image = love.graphics.newImage("assets/sprite.png"),
		--x = 16,
		--y = 16,
		x = objX,
		y = objY - 16,
		r = 0,
		collidable = true,
		canMove = true,
	}

	spriteLayer.player = gPlayer


	world:add(spriteLayer.player,objX,objY,16,16)
	-- Update callback for Custom Layer
	function spriteLayer:update(dt)
		local newX, newY
		--local player = self.player
		local player = gPlayer
		local move = false
		-- 48 pixels per second
		-- aka 3 tiles/s seems to be about right.
		local speed = 48 * dt
		newY = player.y
		newX = player.x
		move = true
		if player.canMove then
			-- Move player up
			if love.keyboard.isDown("w", "up") then
				newY = player.y - 16

			elseif love.keyboard.isDown("s", "down") then
				newY = player.y + 16
				-- Move player left
			elseif love.keyboard.isDown("a", "left") then
				newX = player.x - 16
				-- Move player right
			elseif love.keyboard.isDown("d", "right") then
				newX = player.x + 16
			else
				move = false
			end
		else
			move = false
		end

		if move == true then
			local actualX, actualY, cols, len = world:move(player, newX,newY)
			if len == 0 then
				gPlayer.canMove = false
				Timer.tween(0.5, {
					[gPlayer] = {x = newX, y = newY}
				}):finish(function()

					gPlayer.canMove = true
				end)
			--else
			--	player.x = actualX
			--	player.y = actualY
			end

		end

	end

	-- Draw callback for Custom Layer
	function spriteLayer:draw()
		local sprite = self.player
		local x = math.floor(sprite.x)
		local y = math.floor(sprite.y)
		local r = sprite.r
		love.graphics.draw(sprite.image, x, y, r)
	end

end

function World:update(dt)
	self.map:update(dt)

	--local tile_x,tile_y = self.map:convertPixelToTile(gPlayer.x,gPlayer.y)
	check_teleports(self.map,gPlayer.x,gPlayer.y)
end

--- Checks if the player is on a teleportation tile.
-- @param map The map we're checking.
-- @param x the X coordinate.
-- @param y the y coordinate
function check_teleports(map,x,y)
	for _, obj in pairs(map.objects) do
		if x == obj.x and y+16 == obj.y then
			if(obj.type == "teleport") then
				local tele = map:getObject("teleport_points",obj.properties.to)

				map.layers["Sprite Layer"].player.x = tele.x
				map.layers["Sprite Layer"].player.y = tele.y - 16
			end
			break;
		end
	end
end

function World:render()
	local scale = 2
	love.graphics.setColor(1, 1, 1)
	screen_width = love.graphics.getWidth() / 4
	screen_height = love.graphics.getHeight() / 4

	local tx = math.floor(gPlayer.x - screen_width /2)
	local ty = math.floor(gPlayer.y - screen_height /2)
	--love.graphics.translate(-tx,-ty)
	self.map:draw(-tx,-ty,scale,scale)
	love.graphics.setColor(1,1,1)
	-- Draw Collision Map (useful for debugging)
	love.graphics.setColor(1, 1, 0)
	self.map:bump_draw(world,-tx,-ty,scale,scale)
end
